# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799f643d0d88ad05307b1b8edc95c682e69c339a6d4b0c12c16c2cc43d53c7003ecf2b5cbbbeaf1df93bc64ab2064d90c18e9b4a2b0374b807cfbfd5ec53b873

test:
  secret_key_base: 75e5e6cb022fac2047b3cc5f05b68bb4fdf67f950923232e985f0b1a71a97a3c8f62b10ca2466e74244fb212bfc355c6bf9bc785b9873466720d77c2ffcb46cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
